name: Go Tests
on: [push, pull_request]
jobs:
  go_tests:
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2


      - name: Download Dependencies
        run: go test $(go list ./... | grep -v /appengine/)

      - name: Test
        run: go test $(go list ./... | grep -v /appengine/)
